"""empty message

Revision ID: 27d571c9d82e
Revises: b1d945e9309f
Create Date: 2018-11-16 14:13:31.092000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d571c9d82e'
down_revision = 'b1d945e9309f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('detail_address', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'detail_address')
    # ### end Alembic commands ###
